services:
  db:
    image: postgres:16
    container_name: pleasanter_postgres
    # 認証タイムアウトを 120 秒に延長
    command: ["postgres", "-c", "authentication_timeout=120s"]
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "MyStrongPostgresPass!"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"      #外部疎通用バインド
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pleasanter:
    build:
      context: .
      dockerfile: pleasanter/Dockerfile
    container_name: pleasanter_app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8881:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_PATHBASE: ""
      # サブディレクトリ利用しないので UsePathBase は不要です。
      # ※ アプリ側で必要なら Forwarded Headers の設定は行ってください。

  codedefiner:
    build:
      context: .
      dockerfile: codedefiner/Dockerfile
    container_name: pleasanter_codedefiner
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"

networks:
  default:
    name: pleasanterDocker_default

volumes:
  pg_data:
    name: pleasanterDocker_pg_data
